name: Linting Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v1
      
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
    
    - name: Run Kotlin Linter
      run: ./gradlew ktlintCheck

    - name: Run Android Linter
      run: ./gradlew lintDebug
