name: Linting Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8    
    
    - name: Run Kotlin Linter
      run: ./gradlew ktlintStagingDebugCheck

    - name: Run Android Linter
      run: ./gradlew lintStagingDebug
