name: Release Workflow


on:
  push:
  pull_request:
    branches:
      -main
  workflow_dispatch:

# Based very significantly off of Michael Haaf's workflow at:
# https://github.com/michaelhaaf/KotlinWithCompose/blob/744c5cf5790e3e74575d5d25633438ec72aec7e6/.github/workflows/build.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{runner.os}}-gradle-

      - name: Validate Gradle wrapper binaries
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build
